[package]
name = "dsc_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
thiserror = "1.0"
derive_builder ="0.12"
