bundle_schemas:
  # Resource manifest bundle
  - ConfigFilePath: resource/manifest.yaml
    Name: resource.manifest
    OutputFormat: ['Json', 'JsonVSCode', 'Yaml', 'YamlVSCode']

  # Configuration document bundle
  - ConfigFilePath: config/document.yaml
    Name: config.document
    OutputFormat: ['Json', 'JsonVSCode', 'Yaml', 'YamlVSCode']

  # Output schema bundles
  - ConfigFilePath: outputs/schema.yaml
    Name: outputs.schema
    OutputFormat: ['Json']
  - ConfigFilePath: outputs/config/get.yaml
    Name: outputs.config.get
    OutputFormat: ['Json']
  - ConfigFilePath: outputs/config/set.yaml
    Name: outputs.config.set
    OutputFormat: ['Json']
  - ConfigFilePath: outputs/config/test.yaml
    Name: outputs.config.test
    OutputFormat: ['Json']
  - ConfigFilePath: outputs/config/validate.yaml
    Name: outputs.config.validate
    OutputFormat: ['Json']
  - ConfigFilePath: outputs/resource/get.yaml
    Name: outputs.resource.get
    OutputFormat: ['Json']
  - ConfigFilePath: outputs/resource/list.yaml
    Name: outputs.resource.list
    OutputFormat: ['Json']
  - ConfigFilePath: outputs/resource/schema.yaml
    Name: outputs.resource.schema
    OutputFormat: ['Json']
  - ConfigFilePath: outputs/resource/set.yaml
    Name: outputs.resource.set
    OutputFormat: ['Json']
  - ConfigFilePath: outputs/resource/test.yaml
    Name: outputs.resource.test
    OutputFormat: ['Json']
