trigger: none

variables:
  - name: BuildConfiguration
    value: 'Release'
  - name: PackageRoot
    value: '$(System.ArtifactsDirectory)/Packages'
  - group: DSCAPIScan

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance
    ref: fixApiScanNet6

stages:
- stage: Build
  displayName: Build Native Binaries
  dependsOn: []
  jobs:
  - job: BuildWin
    pool:
      name: PowerShell1ES
      demands:
      - ImageOverride -equals PSMMS2019-Rust-Secure
    displayName: Windows
    strategy:
      matrix:
        Windows x64:
          buildName: x86_64-pc-windows-msvc
        Windows x64_arm64:
          buildName: aarch64-pc-windows-msvc

    steps:
    - pwsh: |
        rustup default stable
        rustup target add $(buildName)
        ./build.ps1 -Release -Architecture $(buildName)
      displayName: 'Build $(buildName)'
      condition: succeeded()
    - pwsh: |
        compress-archive -Path "$(Build.SourcesDirectory)/bin/$(buildName)/$(BuildConfiguration)" -DestinationPath "$(System.ArtifactsDirectory)\Packages\$(buildName).zip"
      displayName: 'Compress $(buildName)'
      condition: succeeded()
    - pwsh: |
        Write-Host "##vso[artifact.upload containerfolder=release;artifactname=release]$(System.ArtifactsDirectory)\Packages\$(buildName).zip"
      displayName: Upload artifacts
      condition: succeeded()

  - job: BuildLinux
    displayName: Linux
    pool:
      name: PowerShell1ES
      demands:
      - ImageOverride -equals PSMMSUbuntu20.04-Secure
    steps:
    - pwsh: |
        rustup default stable
        ./build.ps1 -Release -Architecture x86_64-unknown-linux-gnu
      displayName: 'Build x86_64-unknown-linux-gnu'
      condition: succeeded()
    - pwsh: |
        tar -czvf $(System.ArtifactsDirectory)/Packages/x86_64-unknown-linux-gnu.tar.gz -C $(Build.SourcesDirectory)/bin/$(BuildConfiguration)/x86_64-unknown-linux-gnu .
      displayName: 'Compress x86_64-unknown-linux-gnu'
      condition: succeeded()
    - pwsh: |
        Write-Host "##vso[artifact.upload containerfolder=release;artifactname=release]$(System.ArtifactsDirectory)\Packages\x86_64-unknown-linux-gnu.zip"
      displayName: Upload artifacts
      condition: succeeded()

  - job: BuildLinuxArm64
    displayName: Linux ARM64
    pool:
      name: ps-powershell-rel-arm
      demands:
      - ImageOverride -equals PSMMSUbuntu20.04-ARM64-secure
    steps:
    - pwsh: |
        rustup default stable
        ./build.ps1 -Release -Architecture aarch64-unknown-linux-gnu
      displayName: 'Build aarch64-unknown-linux-gnu'
      condition: succeeded()
    - pwsh: |
        tar -czvf $(System.ArtifactsDirectory)/Packages/aarch64-unknown-linux-gnu.tar.gz -C $(Build.SourcesDirectory)/bin/$(BuildConfiguration)/aarch64-unknown-linux-gnu .
      displayName: 'Compress aarch64-unknown-linux-gnu'
      condition: succeeded()
    - pwsh: |
        Write-Host "##vso[artifact.upload containerfolder=release;artifactname=release]$(System.ArtifactsDirectory)\Packages\aarch64-unknown-linux-gnu.zip"
      displayName: Upload artifacts
      condition: succeeded()


  - job: BuildMac
    displayName: Build Native Binaries on macOS
    pool:
      vmImage: macOS-Latest
    strategy:
      matrix:
        macOS x64:
          buildName: x86_64-apple-darwin
        macOS arm64:
          buildName: aarch64-apple-darwin
    steps:
    - pwsh: |
        rustup default stable
        rustup target add $(buildName)
        ./build.ps1 -Release -Architecture $(buildName)
      displayName: 'Build $(buildName)'
      condition: succeeded()
    - pwsh: |
        tar -czvf $(System.ArtifactsDirectory)/Packages/$(buildName).tar.gz -C $(Build.SourcesDirectory)/bin/$(BuildConfiguration)/$(buildName) .
      displayName: 'Compress $(buildName)'
      condition: succeeded()
    - pwsh: |
        Write-Host "##vso[artifact.upload containerfolder=release;artifactname=release]$(System.ArtifactsDirectory)\Packages\$(buildName).zip"
      displayName: Upload artifacts
      condition: succeeded()

- stage: compliance
  displayName: Compliance
  dependsOn: Build
  jobs:
  - job: Compliance_Job
    pool:
      name: PowerShell1ES
      demands:
      - ImageOverride -equals PSMMS2019-Rust-Secure
    steps:
    - checkout: self
      clean: true
    - checkout: ComplianceRepo
      clean: true

    - download: current
      artifact: release

    - download: current
      artifact: signed

    - pwsh: |
        Get-ChildItem -Path 'ENV:'
      displayName: Capture environment

    - template: assembly-module-compliance.yml@ComplianceRepo
      parameters:
        # binskim
        AnalyzeTarget: '$(Pipeline.Workspace)/uncompressed/*.dll'
        AnalyzeSymPath: 'SRV*'
        # component-governance
        sourceScanPath: '$(Build.SourcesDirectory)/DSC'
        # credscan
        suppressionsFile: ''
        # TermCheck
        optionsRulesDBPath: ''
        optionsFTPath: ''
        # tsa-upload
        codeBaseName: 'DSC'
        # selections
        softwareName: 'DSC'
        softwareNameFolder: '$(Pipeline.Workspace)/uncompressed'
        softwareVersion: '$(PackageVersion)'
        connectionString: RunAs=App;AppId=$(APIScanClient);TenantId=$(APIScanTenant);AppKey=$(APIScanSecret)
        APIScan: true # set to false when not using Windows APIs.
