trigger: none

variables:
  - name: BuildConfiguration
    value: 'Release'
  - name: PackageRoot
    value: '$(System.ArtifactsDirectory)/Packages'
  - group: DSCAPIScan

resources:
  repositories:
  - repository: ComplianceRepo
    type: github
    endpoint: ComplianceGHRepo
    name: PowerShell/compliance
    ref: fixApiScanNet6

stages:
- stage: Build
  displayName: Build Native Binaries
  dependsOn: []
  jobs:
  - job: BuildWin
    pool:
      name: PowerShell1ES
      demands:
      - ImageOverride -equals PSMMS2019-Rust-Secure
    displayName: Windows
    strategy:
      matrix:
        Windows x64:
          buildName: x86_64-pc-windows-msvc
        Windows x64_arm64:
          buildName: aarch64-pc-windows-msvc

    steps:
    - pwsh: |
        rustup target add $(buildName)
        ./build.ps1 -Release -Architecture $(buildName)
      displayName: 'Build $(buildName)'

  - job: BuildLinux
    displayName: Linux
    pool:
      name: PowerShell1ES
      demands:
      - ImageOverride -equals PSMMSUbuntu20.04-Secure
    steps:
    - pwsh: |
        $env:PATH += ':~/.cargo/bin'
        ./build.ps1 -Release -Architecture x86_64-unknown-linux-gnu
      displayName: 'Build x86_64-unknown-linux-gnu'

  - job: BuildLinuxArm64
    displayName: Linux ARM64
    pool:
      name: PowerShell1ES
      demands:
      - ImageOverride -equals PSMMSUbuntu20.04-ARM64-secure
    steps:
    - pwsh: |
        $env:PATH += ':~/.cargo/bin'
        ./build.ps1 -Release -Architecture aarch64-unknown-linux-gnu
      displayName: 'Build aarch64-unknown-linux-gnu'

  - job: BuildMac
    displayName: Build Native Binaries on macOS
    pool:
      vmImage: macOS-Latest
    strategy:
      matrix:
        macOS x64:
          buildName: x86_64-apple-darwin
        macOS arm64:
          buildName: aarch64-apple-darwin
    steps:
    - pwsh: |
        rustup target add $(buildName)
        ./build.ps1 -Release -Architecture $(buildName)
      displayName: 'Build $(buildName)'

- stage: compliance
  displayName: Compliance
  dependsOn: Build
  jobs:
  - job: Compliance_Job
    pool:
      name: PowerShell1ES
      demands:
      - ImageOverride -equals PSMMS2019-Rust-Secure
    steps:
    - checkout: self
      clean: true
    - checkout: ComplianceRepo
      clean: true

    - download: current
      artifact: release

    - download: current
      artifact: signed

    - pwsh: |
        Get-ChildItem -Path 'ENV:'
      displayName: Capture environment

    - template: assembly-module-compliance.yml@ComplianceRepo
      parameters:
        # binskim
        AnalyzeTarget: '$(Pipeline.Workspace)/uncompressed/*.dll'
        AnalyzeSymPath: 'SRV*'
        # component-governance
        sourceScanPath: '$(Build.SourcesDirectory)/DSC'
        # credscan
        suppressionsFile: ''
        # TermCheck
        optionsRulesDBPath: ''
        optionsFTPath: ''
        # tsa-upload
        codeBaseName: 'DSC'
        # selections
        softwareName: 'DSC'
        softwareNameFolder: '$(Pipeline.Workspace)/uncompressed'
        softwareVersion: '$(PackageVersion)'
        connectionString: RunAs=App;AppId=$(APIScanClient);TenantId=$(APIScanTenant);AppKey=$(APIScanSecret)
        APIScan: true # set to false when not using Windows APIs.
